build-aux/flatpak/ca.andyholmes.Valent.json, src/plugins/runcommand/ca.andyholmes.valent.runcommand.gschema.xml, src/plugins/runcommand/meson.build, src/plugins/runcommand/valent-runcommand-plugin.c, src/plugins/runcommand/valent-runcommand-preferences.c, src/plugins/runcommand/valent-runcommand-preferences.ui, src/plugins/runcommand/valent-runcommand-utils.c, src/plugins/runcommand/valent-runcommand-utils.h
Drop the `--talk=org.freedesktop.Flatpak` permission and default to
executing commands with `flatpak-spawn` when available.
Flatpak users will have to manually poke a hole in the sandbox to
execute commands on the host and all users will have to disable the
`isolate-subprocesses` setting, which comes with a warning.
This is more inconvenient for the common use-case of the plugin, which
typically involves running commands on the host, but it prevents user
plugins from arbitrarily executing commands on the host for flatpak
users.
=> Runcommand Plugin: make the runcommand plugin more secure by default

.github/workflows/ci.yml, src/plugins/notification/valent-notification-preferences.c, src/tests/extra/lsan.supp, src/tests/fixtures/meson.build, src/tests/fixtures/valent-test-utils.c, src/tests/fixtures/valent-test-utils.h, src/tests/plugins/battery/meson.build, src/tests/plugins/battery/test-battery-preferences.c, src/tests/plugins/clipboard/meson.build, src/tests/plugins/clipboard/test-clipboard-preferences.c, src/tests/plugins/contacts/meson.build, src/tests/plugins/contacts/test-contacts-preferences.c, src/tests/plugins/notification/meson.build, src/tests/plugins/notification/test-notification-preferences.c, src/tests/plugins/runcommand/meson.build, src/tests/plugins/runcommand/test-runcommand-preferences.c, src/tests/plugins/telephony/meson.build, src/tests/plugins/telephony/test-telephony-preferences.c
Add some basic tests for plugin preferences, just to ensure they don't
blow up or leak when constructed and disposed.
=> tests: add basic smoke tests for plugin preferences

data/ca.andyholmes.Valent.xml, po/en.po, po/valent.pot, src/libvalent/core/data/ca.andyholmes.Valent.Device.xml, src/libvalent/core/meson.build, src/libvalent/core/valent-device.c, src/libvalent/core/valent-device.h, src/libvalent/core/valent-manager.c, src/libvalent/ui/valent-device-panel.c, src/libvalent/ui/valent-device-panel.ui
Improve the pairing UX by adding a `state` flags property to `ValentDevice`
that includes ongoing pairing processes and clean up the UI in
`ValentDevicePanel`.
=> Pairing UX

src/plugins/mpris/valent-mpris-remote.c, src/tests/libvalent/core/test-task-queue.c, src/tests/plugins/mpris/test-mpris-component.c
* ValentMprisRemote: minor fixes and cleanup
* consume pending properties while preparing emission
* remove flush GSource when unexported
* fix timeout in test-mpris-component
* fix timeout in test-task-queue
=> test: fix test-mpris-component and test-task-queue

src/tests/plugins/lan/test-lan-plugin.c, src/tests/plugins/mpris/test-mpris-plugin.c
* use some defines in "lan" plugin tests
* add missing ifdef for "mpris" fuzzing
=> tests: minor cleanups

src/plugins/lan/valent-lan-channel-service.c, src/plugins/lan/valent-lan-channel-service.h, src/plugins/lan/valent-lan-utils.c, src/plugins/lan/valent-lan-utils.h, src/tests/extra/tsan.supp
* ValentLanChannelService
* remove unused property accessor
* connect to GThreadedSocketService::run instead of overriding vfunc
* drop port number assertions in favour of reasonable GParamSpec range
* trigger cancellable in stop()
* lan-utils: cleanup some comments and code style
=> lan plugin: various cleanups

src/plugins/eds/valent-ebook-store.c
The ValentContactStore instance was not being passed through
`e_client_wait_for_connected()`.
=> ValentEBookStore: fix missing callback data

src/tests/fixtures/valent-mock-channel-service.c, src/tests/fixtures/valent-test-plugin-fixture.c, src/tests/fixtures/valent-test-utils.h, src/tests/libvalent/clipboard/test-clipboard-component.c, src/tests/libvalent/contacts/test-contacts-component.c, src/tests/libvalent/core/test-device.c, src/tests/libvalent/core/test-manager.c, src/tests/libvalent/input/test-input-component.c, src/tests/libvalent/media/test-media-component.c, src/tests/libvalent/mixer/test-mixer-component.c, src/tests/libvalent/notifications/test-notifications-component.c, src/tests/libvalent/session/test-session-component.c, src/tests/plugins/fdo/test-fdo-notifications.c, src/tests/plugins/fdo/test-fdo-session.c, src/tests/plugins/gtk/test-gdk-clipboard.c, src/tests/plugins/gtk/test-gtk-notifications.c, src/tests/plugins/lan/test-lan-plugin.c, src/tests/plugins/mpris/test-mpris-component.c
Add version of `g_assert_finalize_object()` that actually tells you
where the object is that failed to finalize.
Also, rename the current macro `v_assert_finalize_object()` to
`v_await_finalize_object()` to reflect its actual behaviour.
=> tests: add a more helpful version of g_assert_finalize_object()

src/libvalent/ui/valent-plugin-row.c, src/libvalent/ui/valent-window.ui
Fix enabling and disabling network components, which were being passed a
`plugin-context` of `channel` instead of `network` in
`valent-window.ui`.
Also use `valent_component_new_settings()` in `ValentPluginRow` to
ensure the same GSettings path is being used.
=> libvalent-ui: fix enable/disable for network plugins

src/libvalent/core/valent-device-plugin.c, src/libvalent/core/valent-device-plugin.h, src/libvalent/core/valent-device.c, src/plugins/battery/valent-battery-plugin.c, src/plugins/clipboard/valent-clipboard-plugin.c, src/plugins/contacts/valent-contacts-plugin.c, src/plugins/findmyphone/valent-findmyphone-plugin.c, src/plugins/lock/valent-lock-plugin.c, src/plugins/mousepad/valent-mousepad-plugin.c, src/plugins/mpris/valent-mpris-plugin.c, src/plugins/notification/valent-notification-plugin.c, src/plugins/photo/valent-photo-plugin.c, src/plugins/ping/valent-ping-plugin.c, src/plugins/runcommand/valent-runcommand-plugin.c, src/plugins/sftp/valent-sftp-plugin.c, src/plugins/share/valent-share-plugin.c, src/plugins/sms/valent-sms-plugin.c, src/plugins/systemvolume/valent-systemvolume-plugin.c, src/plugins/telephony/valent-telephony-plugin.c, src/tests/fixtures/packetless-plugin.c, src/tests/fixtures/valent-mock-device-plugin.c
Every plugin that implements this interface immediately makes calls to
`valent_device_get_connected()` and `valent_device_get_paired()`, which
both involve locking a mutex now.
Since plugins are always interested in the device state, get that via a
single call to `valent_device_get_state()` and pass it as an argument.
=> ValentDevicePlugin: optimize valent_device_plugin_update_state()

src/libvalent/core/valent-debug.h.in, src/libvalent/ui/valent-application.c, src/plugins/telephony/valent-telephony-plugin.c
Rather than having the GApplication::activate handler call the
preferences action, which is kind of weird, have them both call a
new `valent_application_present_window()` function.
This comes with a `startup_id` argument, which might be useful sometime?
=> ValentApplication: break window presentation code into a function

src/libvalent/core/valent-device.c, src/libvalent/core/valent-manager.c, src/libvalent/core/valent-packet.c, src/libvalent/core/valent-packet.h, src/plugins/battery/valent-battery-plugin.c, src/plugins/bluez/valent-bluez-channel.c, src/plugins/clipboard/valent-clipboard-plugin.c, src/plugins/contacts/valent-contacts-plugin.c, src/plugins/lan/valent-lan-channel-service.c, src/plugins/lan/valent-lan-channel.c, src/plugins/lock/valent-lock-plugin.c, src/plugins/mousepad/valent-mousepad-plugin.c, src/plugins/mpris/valent-mpris-plugin.c, src/plugins/notification/valent-notification-plugin.c, src/plugins/photo/valent-photo-plugin.c, src/plugins/ping/valent-ping-plugin.c, src/plugins/runcommand/valent-runcommand-plugin.c, src/plugins/sftp/valent-sftp-plugin.c, src/plugins/share/valent-share-plugin.c, src/plugins/systemvolume/valent-systemvolume-plugin.c, src/plugins/telephony/valent-telephony-plugin.c, src/tests/fixtures/valent-mock-channel.c, src/tests/libvalent/core/test-packet.c, src/tests/plugins/lan/test-lan-plugin.c
Replace the `valent_packet_check_*` macros with functions that operate
on the packet `JsonNode`.
The semantics of the functions make more sense and are more convenient
in C where they take a pointer to the field type and return a success
boolean.
These are a bit slower, but safer and make it easier to warn when a
packet is malformed.
=> valent-packet: replace macros with convenience function

src/libvalent/core/valent-device.c, src/libvalent/core/valent-utils.c, src/libvalent/ui/valent-application.c, src/tests/extra/setup.cfg
Change the GVariant format of the `app.device` GAction from `(ssbv)` to
`(ssav)`. This is a more conventional approach to passing option action
targets, and a little bit less clunky.
=> ValentApplication: change the format of the `app.device` GAction

src/plugins/battery/valent-battery-plugin.c, src/plugins/battery/valent-battery.c, src/plugins/battery/valent-battery.h, src/tests/plugins/battery/mock_upower.py, src/tests/plugins/battery/test-battery.c
Refactor the UPower abstraction used by the battery plugin to better
abstract UPower particulars to the simple values KDE Connect uses.
* drop GObject properties
* use getters that reflect `kdeconnect.battery` packet fields
* handle `State` and `WarningLevel` properties thoroughly
* handle changes to the `IsPresent` property
=> ValentBattery: refactor and handle UPower states more thoroughly

src/tests/extra/Dockerfile
The image from docker.io seems to be lagging behind the image from
registry.fedoraproject.org, which causes the image build to choke up.
Switch to Fedora's canonical registry, while bumping the image to 36.
=> tests: bump CI image to fedora:36 and use Fedora's registry

src/tests/extra/Dockerfile
* remove the COPR repository for glib2
The `EPERM` patch has been added upstream, so we don't need to carry
a custom package build anymore.
* add a wildcard for debuginfo repositories
Some debuginfo's seem to be hanging around in updates-testing for
now, causing the ASAN job to fail.
=> tests: update Dockerfile for changes in fedora:36

doc/sdk/urlmap.js, doc/sdk/valent.toml.in, src/libvalent/ui/valent-menu-list.c, src/libvalent/ui/valent-menu-list.h, src/libvalent/ui/valent-menu-stack.c, src/libvalent/ui/valent-preferences-window.ui, src/libvalent/ui/valent-window.ui, src/plugins/runcommand/valent-runcommand-editor.c, src/tests/plugins/runcommand/meson.build, src/tests/plugins/runcommand/test-runcommand-editor.c
* ValentWindow
* move shortcut controller to the root widget
* add a primary menu item to quit Valent
* ValentPreferencesWindow: mark missed string as translatable
* ValentMenuList, ValentMenuStack
* rename "model" property to "menu-model"
* fix a segmentation fault with sections
=> libvalent-ui: minor fixes

.github/workflows/cr.yml
The CI image was incorrectly checking `github.ref == 'refs/head/main'`
when it should have been `github.ref == 'refs/heads/main'`.
Regardless, change it to publish whenever the event is not a pull
request.
=> cr: fix publish conditional

build-aux/flatpak/ca.andyholmes.Valent.Devel.json, build-aux/flatpak/ca.andyholmes.Valent.json, src/plugins/xdp/meson.build, subprojects/libportal.wrap
libportal-0.6 didn't seem to break any ABI/API used in the XDP plugin,
so allow building with either v0.5 or v0.6.
=> xdp module: allow building with libportal >= 0.5 && <= 0.6

src/tests/extra/Dockerfile
Remove `alsa-lib-devel` and don't install weak dependencies.
=> test: cleanup CI image

src/tests/extra/Dockerfile
Explicitly install debuginfo from `fedora-debuginfo` and
`updates-debuginfo` to avoid pulling in mismatched debug packages.
=> tests: fix Dockerfile debuginfo install

src/plugins/mousepad/valent-mousepad-plugin.c, src/tests/plugins/mousepad/test-mousepad-plugin.c
Add a method tailored to the plugin for toggling plugin actions based on
the device state and the remote keyboard state.
=> mousepad: add valent_mousepad_plugin_toggle_actions()

.github/dependabot.yml, .github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/cr.yml, src/libvalent/core/libvalent-core.h, src/libvalent/core/valent-data.h, src/libvalent/core/valent-device-manager.c, src/libvalent/core/valent-device.c, src/libvalent/media/libvalent-media.h, src/libvalent/mixer/libvalent-mixer.h, src/plugins/mousepad/valent-mousepad-plugin.c, src/plugins/notification/valent-notification-plugin.c, src/plugins/presenter/valent-presenter-plugin.c, src/plugins/sms/valent-sms-plugin.c, src/tests/libvalent/meson.build
* libvalent: add enum headers to public header
* ValentDeviceManager: fix missing chain-up in dispose
* ValentDevice: missing `G_PARAM_EXPLICIT_NOTIFY` flag on property
* add GTK initialization guards to plugins
* ci: missing `${{ always() }}` on codespell check
* ci: bump actions/upload-artifact, docker/build-push-action,
docker/login-action, docker/setup-qemu-action
* github: add dependabot configuration
* code style cleanups
=> maintenance: various fixes and cleanups

src/libvalent/clipboard/valent-clipboard.c, src/libvalent/contacts/valent-contacts.c, src/libvalent/core/meson.build, src/libvalent/core/valent-component-private.h, src/libvalent/core/valent-component.c, src/libvalent/core/valent-component.h, src/libvalent/core/valent-device-manager.c, src/libvalent/input/valent-input.c, src/libvalent/media/valent-media.c, src/libvalent/mixer/valent-mixer.c, src/libvalent/notifications/valent-notifications.c, src/libvalent/session/valent-session.c, src/libvalent/ui/valent-application.c, src/libvalent/ui/valent-preferences-window.c, src/tests/libvalent/clipboard/test-clipboard-component.c, src/tests/libvalent/contacts/test-contacts-component.c, src/tests/libvalent/core/test-device-manager.c, src/tests/libvalent/input/test-input-component.c, src/tests/libvalent/media/test-media-component.c, src/tests/libvalent/mixer/test-mixer-component.c, src/tests/libvalent/notifications/test-notifications-component.c, src/tests/libvalent/session/test-session-component.c, src/tests/libvalent/ui/test-application.c, src/tests/plugins/fdo/test-fdo-notifications.c, src/tests/plugins/fdo/test-fdo-session.c, src/tests/plugins/gtk/test-gdk-clipboard.c, src/tests/plugins/gtk/test-gtk-notifications.c, src/tests/plugins/mpris/test-mpris-component.c, src/tests/plugins/systemvolume/test-systemvolume-plugin.c
* fix tear-down in component tests
* replace the `extension-added` and `extension-removed` signals with
the virtual functions `enable_extension` and `disable_extension`
* privatize the automatic selection of the primary adapter
* rename `valent_component_new_settings()` to
`valent_component_create_settings()`.
=> ValentComponent: refactor and cleanup

.github/workflows/ci.yml
There's no reason to avoid running tests for missing licensing, since
that can be fixed before merge. Allow tests to run in spite of a license
exception by running the REUSE check in parallel instead of part of the
linter check.
=> ci: move REUSE compliance to a separate job

.github/workflows/ci.yml
As with the REUSE check, allow the tests to run in case of failure while
still requiring the check to pass before merging.
=> ci: move Codespell to a separate job

src/libvalent/contacts/valent-contact-cache.c, src/libvalent/contacts/valent-contact-store.c, src/libvalent/contacts/valent-contact-store.h, src/plugins/contacts/valent-contacts-plugin.c, src/plugins/eds/valent-ebook-store.c, src/tests/libvalent/contacts/test-contacts-component.c, src/tests/plugins/sms/test-sms-common.h
* add `remove_contacts()` and refact `remove_contact()` as a wrapper
* rename `add_finish()` to `add_contacts_finish()`
* rename `remove_finish()` to` `remove_contacts_finish()`
=> ValentContactStore: minor API cleanups

data/gsettings/ca.andyholmes.valent.device.gschema.xml, po/POTFILES, po/en.po, po/valent.pot, src/libvalent/core/valent-device.c, src/libvalent/core/valent-device.h, src/libvalent/ui/valent-device-preferences-window.c, src/libvalent/ui/valent-device-preferences-window.ui, src/plugins/photo/valent-photo-plugin.c, src/plugins/share/ca.andyholmes.valent.share.gschema.xml, src/plugins/share/meson.build, src/plugins/share/share-plugin.c, src/plugins/share/share.gresource.xml, src/plugins/share/valent-share-plugin.c, src/plugins/share/valent-share-preferences.c, src/plugins/share/valent-share-preferences.h, src/plugins/share/valent-share-preferences.ui, src/tests/fixtures/valent-mock-device-plugin.c, src/tests/libvalent/core/test-device-transfer.c, src/tests/libvalent/core/test-device.c, src/tests/libvalent/ui/test-device-preferences-window.c, src/tests/plugins/share/meson.build, src/tests/plugins/share/test-share-download.c, src/tests/plugins/share/test-share-preferences.c
Although ostensibly convenient for third-party plugins, the download
folder setting makes more sense as a part of the share plugin; as it is
in KDE Connect.
=> ValentDevice: relocate download-folder setting to the share plugin

src/libvalent/core/valent-device-manager.c, src/libvalent/core/valent-device-private.h, src/libvalent/core/valent-device.c, src/libvalent/core/valent-device.h, src/tests/fixtures/valent-test-fixture.c, src/tests/libvalent/core/test-device.c
By the time `valent_device_handle_packet()` is called we know the type
is non-NULL, so use `strcmp()` to take advantage of any optimizations
the compiler can perform.
=> ValentDevice: use strcmp() in hot path

src/libvalent/core/valent-application-plugin.c, src/libvalent/core/valent-application-plugin.h, src/libvalent/ui/valent-application.c, src/tests/fixtures/valent-mock-application-plugin.c, src/tests/libvalent/core/meson.build, src/tests/libvalent/core/test-application-plugin.c
Refactor ValentApplicationPlugin to handle more GApplication virtual
functions including `activate()`, `command_line()` and `open()`. This
allows delegating these operations to plugins, such as the `share`
which can then serve as the defacto URI handler.
* add `activate()`, `command_line()` and `open()` virtual functions
* add `device-manager` property to `ValentApplicationPlugin`
* add property accessors for `application` and `device-manager`
=> refactor(plugins): expand ValentApplicationPlugin class

meson.build, src/libvalent/meson.build
Even though libvalent is not stable we need to exclude the pre-release
suffix, because it results in an invalid version being generated in the
`.pc` file.
=> fix(build): use a valid version in `pkgconfig` file

.github/workflows/ci.yml, src/libvalent/core/valent-device-manager.c, src/tests/extra/cppcheck.cfg, src/tests/extra/cppcheck.supp
Remove the `unknownMacro` suppressions and add `cppcheck.cfg` with
proper macro definitions, until the macros are included upstream.
=> ci: cleanup cppcheck config

src/plugins/telephony/valent-telephony-plugin.c, src/tests/fixtures/glibtest.py
If a test run with the `glibtest.py` wrapper, or a dbusmock derivation,
times out, be sure to propagate the output to aid in debugging.
Unfortunately, if the meson timeout is reached before the script's then
the process is killed and the output never propagated. Make a note of
this if someone goes looking for a reason.
=> test: propagate output from python wrapper for timeouts

src/libvalent/core/valent-certificate.c, src/plugins/lan/valent-lan-channel-service.c, src/plugins/lan/valent-lan-utils.c, src/plugins/lan/valent-lan-utils.h, src/tests/plugins/lan/test-lan-plugin.c
The TLS certificate is the single source of truth for a device's ID, so
never trust the ID from the identity packet.
=> fix(lan): never trust the device ID from the identity packet

build-aux/flatpak/ca.andyholmes.Valent.Tests.json
When running flatpak tests, use `type: dir` for sources so tests are run
on the current `HEAD` commit instead of `type: git` which resulted in
tests being run on the current revision in the `main` branch.
=> test(ci): use `dir` type for sources in flatpak test manifest

src/libvalent/core/valent-device-manager.c, src/plugins/lan/valent-lan-channel-service.c, src/plugins/lan/valent-lan-channel.c, src/plugins/lan/valent-lan-channel.h, src/tests/data/plugin-lan.json, src/tests/fixtures/valent-mock-channel.c, src/tests/plugins/lan/test-lan-plugin.c
A number of potential vulnerabilities in `kdeconnect-kde` identified in
CVE-2020-26164[1] also affect Valent. The summary here references the
security review report[2] published by Matthias Gerstner.
Of the 8 security issues (3.a-h), 4 are applicable (3.d, 3.e, 3.f, 3.h), 2 are
not applicable (3.b, 3.c), and 2 were previously addressed (3.a, 3.g).
When reading the identity from an incoming connection, set a limit of
8KiB for the peer identity packet.
When handling a new `ValentChannel`, limit the maximum number of
concurrent unpaired connections to 10.
When accepting an incoming connection, set a timeout of 1000ms for the
peer to write its identity packet and negotiate a TLS connection.
When receiving an incoming broadcast, limit outgoing connections to the
protocol port range …
=> fix: address potential exploits from CVE-2020-26164

src/plugins/lan/valent-lan-channel-service.c, src/plugins/lan/valent-lan-channel.c, src/tests/plugins/lan/test-lan-plugin.c
Refactor the `certificate` property  of `ValentLanChannel` to match
`peer-certificate`, proxying the `GTlsConnection` properties.
=> refactor(lan): make channel "certificate" property read-only

data/ca.andyholmes.Valent.xml, src/libvalent/core/valent-device-impl.c, src/libvalent/core/valent-device-manager.c, src/libvalent/core/valent-device.c, src/libvalent/core/valent-device.h, src/libvalent/ui/valent-device-preferences-window.c, src/tests/libvalent/core/test-device.c
The `Valent.Device:paired` property is rarely needed in isolation, so
migrate the few remaining uses and remove it from the public API, in
favour of `Valent.Device:state`.
=> refactor(device): remove the "paired" property

data/ca.andyholmes.Valent.xml, src/libvalent/core/valent-device-impl.c, src/libvalent/core/valent-device.c, src/libvalent/core/valent-device.h, src/plugins/notification/valent-notification-plugin.c, src/tests/libvalent/core/test-device.c
As with `Valent.Device:property`, this connected state is better
expressed by the `Valent.Device:state` property. Remove this property
from the public API and D-Bus interface.
=> refactor(device): remove the "connected" property

src/tests/fixtures/valent-test-fixture.c, src/tests/fixtures/valent-test-fixture.h, src/tests/fixtures/valent-test-utils.c, src/tests/fixtures/valent-test-utils.h, src/tests/libvalent/core/test-device-transfer.c, src/tests/libvalent/core/test-device.c, src/tests/plugins/notification/test-notification-plugin.c, src/tests/plugins/share/test-share-download.c
* rename `valent_test_channels()` to `valent_test_channel_pair()`
* move `valent_test_fixture_wait()` to `valent_test_wait()` and iterate
the default main context instead of a `GMainLoop`
* cleanup assertion macros, using more useful log messages and variable
names that won't conflict with surrounding code
=> test(fixtures): cleanup some helpers

src/libvalent/clipboard/valent-clipboard-adapter.c, src/libvalent/clipboard/valent-clipboard-adapter.h, src/libvalent/clipboard/valent-clipboard.c, src/libvalent/clipboard/valent-clipboard.h, src/plugins/clipboard/valent-clipboard-plugin.c, src/plugins/gtk/valent-gdk-clipboard.c, src/tests/extra/lsan.supp, src/tests/fixtures/valent-mock-clipboard-adapter.c, src/tests/libvalent/clipboard/test-clipboard-component.c, src/tests/plugins/clipboard/test-clipboard-plugin.c, src/tests/plugins/gtk/test-gdk-clipboard.c
A hopefully final pass at the clipboard in Valent.
* add a generic getter/setter that exchanges `GBytes`
* add mime-types getter
* cleanup and expand the tests
=> Clipboard Refactor

src/tests/plugins/notification/meson.build, src/tests/plugins/share/test-share-upload.c
Fix a couple recurring test failures that are preventing the CI from
passing; both are false positives.
=> test: fix bogus test failures

src/libvalent/core/valent-channel-service.c, src/libvalent/core/valent-device-plugin.c, src/libvalent/core/valent-device.c, src/plugins/battery/battery.plugin.desktop.in, src/plugins/clipboard/clipboard.plugin.desktop.in, src/plugins/connectivity_report/connectivity_report.plugin.desktop.in, src/plugins/contacts/contacts.plugin.desktop.in, src/plugins/findmyphone/findmyphone.plugin.desktop.in, src/plugins/lock/lock.plugin.desktop.in, src/plugins/mousepad/mousepad.plugin.desktop.in, src/plugins/mpris/mpris.plugin.desktop.in, src/plugins/notification/notification.plugin.desktop.in, src/plugins/photo/photo.plugin.desktop.in, src/plugins/ping/ping.plugin.desktop.in, src/plugins/presenter/presenter.plugin.desktop.in, src/plugins/runcommand/runcommand.plugin.desktop.in, src/plugins/sftp/sftp.plugin.desktop.in, src/plugins/share/share.plugin.desktop.in, src/plugins/sms/sms.plugin.desktop.in, src/plugins/systemvolume/systemvolume.plugin.desktop.in, src/plugins/telephony/telephony.plugin.desktop.in, src/tests/fixtures/mock.plugin
Rename `X-IncomingCapabilities` and `X-OutgoingCapabilities` fields to
`X-DevicePluginIncoming` and `X-DevicePluginOutgoing` respectively, to
better reflect that these are plugin attributes.
=> refactor(device-plugin): rename incoming/outgoing packet fields

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml
Modify workflows to use `${{ github.repository }}` in place of `andyholmes/valent`, so that forks can pull their own images if they make relevant changes.
=> ci: use container image from current repository

po/en.po, po/valent.pot, src/libvalent/ui/valent-application.c, src/libvalent/ui/valent-device-panel.c, src/libvalent/ui/valent-device-panel.h, src/libvalent/ui/valent-window.c, src/tests/libvalent/ui/test-application.c, src/tests/libvalent/ui/test-device-panel.c, src/tests/libvalent/ui/test-device-preferences-window.c, src/tests/libvalent/ui/test-window.c
* rename the `app.preferences` action to `app.window` and add a string
for opening the window at a specific page
* rename the `win.device` action to `win.page` and always fallback to
the main page to allow passing an empty string
* relay activation of `app.window` to `win.page`
=> feat(ui): allow opening the main window to a specific page

doc/schemas/kdeconnect.mpris.json, doc/schemas/kdeconnect.mpris.request.json, src/libvalent/media/valent-media-player.c, src/libvalent/media/valent-media-player.h, src/plugins/mpris/meson.build, src/plugins/mpris/valent-mpris-adapter.c, src/plugins/mpris/valent-mpris-player.c, src/plugins/mpris/valent-mpris-player.h, src/plugins/mpris/valent-mpris-plugin.c, src/plugins/mpris/valent-mpris-remote.c, src/plugins/mpris/valent-mpris-remote.h, src/plugins/mpris/valent-mpris-utils.c, src/plugins/mpris/valent-mpris-utils.h, src/tests/data/plugin-mpris.json, src/tests/extra/cppcheck.supp, src/tests/fixtures/valent-mock-media-player.c, src/tests/libvalent/media/test-media-component.c, src/tests/plugins/mpris/test-mpris-common.h, src/tests/plugins/mpris/test-mpris-component.c, src/tests/plugins/mpris/test-mpris-plugin.c, src/tests/plugins/mpris/test-mpris-remote.c
There are some oddities in the API for `ValentMediaPlayer`, some
specific to MPRIS and others just clever mistakes.
Cleanup the API in general and break out the properties so cleverly
amalgamated in `ValentMediaPlayer::state`.
=> refactor(media): refactor media players and properties

.github/workflows/cd.yml, .github/workflows/ci.yml, build-aux/flatpak/ca.andyholmes.Valent.Devel.Tests.json, src/tests/libvalent/core/test-device-transfer.c, src/tests/plugins/share/test-share-upload.c
* Setting file `mtime` doesn't work in flatpak, so skip these checks when running in a flatpak environment.
* Update the Flatpak actions to point to a custom fork with support for D-Bus tests
* Add a separate manifest for test on the `gnome-nightly`
=> fix: update flatpak-github-actions and skip broken tests

build-aux/docker/Dockerfile
As with the previous release cycle, add back the `EPERM` patch necessary for some utilities to run in GitHub Actions.
=> ci: update CI to pull custom glib2

src/libvalent/core/valent-channel.c, src/libvalent/core/valent-device-manager.c, src/libvalent/core/valent-device-manager.h, src/libvalent/core/valent-device.c, src/libvalent/ui/valent-application.c, src/libvalent/ui/valent-window.c, src/plugins/lan/valent-lan-channel-service.c, src/plugins/lan/valent-lan-utils.c, src/plugins/lan/valent-lan-utils.h, src/plugins/share/valent-share-target-chooser.c, tests/extra/ci-runner.sh, tests/libvalent/clipboard/test-clipboard-component.c, tests/libvalent/contacts/test-contacts-component.c, tests/libvalent/core/test-application-plugin.c, tests/libvalent/core/test-channel-service.c, tests/libvalent/core/test-data.c, tests/libvalent/core/test-device-manager.c, tests/libvalent/core/test-device-plugin.c, tests/libvalent/core/test-device.c, tests/libvalent/core/test-packet.c, tests/libvalent/input/test-input-component.c, tests/libvalent/media/test-media-component.c, tests/libvalent/mixer/test-mixer-component.c, tests/libvalent/notifications/test-notifications-component.c, tests/libvalent/session/test-session-component.c, tests/plugins/bluez/test-bluez-plugin.c, tests/plugins/lan/test-lan-plugin.c, tests/plugins/share/test-share-target-chooser.c
* cleanups and refactoring for the `lan` plugin
* remove `target` argument from `Valent.DeviceManager.identify`
* various miscellaneous doc and annotation cleanups
=> style: various cleanups and refactoring

src/libvalent/clipboard/valent-clipboard.c, src/libvalent/core/valent-component-private.h, src/libvalent/core/valent-component.c, src/libvalent/core/valent-component.h, src/libvalent/input/valent-input.c, src/libvalent/mixer/valent-mixer.c, src/libvalent/session/valent-session.c, tests/fixtures/valent-test-utils.c
Add a virtual function for components that abstract a single extension and only want to bind to the preferred adapter.
=> feat(core): add `Valent.Component.bind_preferred` vfunc 

meson.build, src/libvalent/ui/valent-ui-utils.c, src/plugins/fdo/valent-fdo-notifications.c, src/plugins/runcommand/valent-runcommand-utils.c, tests/fixtures/glibtest.py
Remove the `G_REGEX_MATCH_DEFAULT` flag from usage, since it's not available until `glib-2.74`.
Add the `-DGLIB_VERSION_MAX_ALLOWED` compile-time flag to prevent future mistakes, and wrap any exceptions to the rule in version-check and ignore-deprecation macros.
=> fix: remove symbols from GLib included in future versions

meson.build, src/libvalent/clipboard/meson.build, src/libvalent/contacts/meson.build, src/libvalent/core/meson.build, src/libvalent/device/meson.build, src/libvalent/device/valent-channel.c, src/libvalent/input/meson.build, src/libvalent/media/meson.build, src/libvalent/meson.build, src/libvalent/mixer/meson.build, src/libvalent/notifications/meson.build, src/libvalent/session/meson.build, src/libvalent/ui/meson.build, src/libvalent/ui/valent-device-gadget.c, src/libvalent/ui/valent-device-gadget.h, src/main.c, src/meson.build, src/plugins/battery/valent-battery-gadget.c, src/plugins/battery/valent-battery-gadget.h, src/plugins/connectivity_report/valent-connectivity_report-gadget.c, src/plugins/connectivity_report/valent-connectivity_report-gadget.h, src/plugins/lock/valent-lock-gadget.c, src/plugins/lock/valent-lock-gadget.h, tests/extra/ci-runner.sh, tests/fixtures/meson.build, tests/fixtures/valent-mock-device-gadget.c, tests/fixtures/valent-mock-device-gadget.h
Since we depend on libportal anyways, move the singleton to the global utilities so it can be used by other sub-libraries and plugins.
=> chore: miscellaneous cleanups

src/libvalent/device/valent-device.c, src/libvalent/device/valent-device.h, src/libvalent/ui/valent-device-page.c, src/libvalent/ui/valent-device-preferences-window.c, src/plugins/runcommand/valent-runcommand-plugin.c, tests/fixtures/valent-test-fixture.c, tests/libvalent/device/test-device.c
Instead of using json-glib's convenience function for serializing GVariant to JSON, build the command list manually so the dictionary can be used to store other settings without leaking it to remote devices.
=> refactor(runcommand): build command list manually

src/plugins/presenter/valent-presenter-remote.ui
The presentation remote uses a custom titlebar, which was missing the start-side window control area resulting in missing buttons for users with alternate button layouts.
fixes #374
=> fix(presenter): add missing window controls to presentation remote

data/metainfo/ca.andyholmes.Valent.metainfo.xml.in.in
Sometime recently `appstreamcli` started considering the duplicate custom key recommended by Purism.
Remove the `workstation` key to appease `appstreamcli validate`, since we're really only trying to convery support for mobile.
=> fix: remove duplicated "Purism::form_factor" tag from metainfo

src/libvalent/ui/valent-device-page.c, src/libvalent/ui/valent-device-preferences-window.c, src/libvalent/ui/valent-preferences-window.c, src/libvalent/ui/valent-window.c, src/plugins/battery/valent-battery-preferences.c, src/plugins/clipboard/valent-clipboard-preferences.c, src/plugins/connectivity_report/valent-connectivity_report-preferences.c, src/plugins/contacts/valent-contacts-preferences.c, src/plugins/mousepad/valent-mousepad-remote.c, src/plugins/mpris/valent-mpris-remote.c, src/plugins/notification/valent-notification-dialog.c, src/plugins/notification/valent-notification-preferences.c, src/plugins/presenter/valent-presenter-remote.c, src/plugins/runcommand/valent-runcommand-editor.c, src/plugins/runcommand/valent-runcommand-preferences.c, src/plugins/sftp/valent-sftp-preferences.c, src/plugins/share/valent-share-preferences.c, src/plugins/share/valent-share-target-chooser.c, src/plugins/share/valent-share-text-dialog.c, src/plugins/sms/valent-sms-conversation.c, src/plugins/sms/valent-sms-window.c, src/plugins/telephony/valent-telephony-preferences.c
We depend on GTK 4.8 now, and this is recommended practice.
=> fix: call `gtk_widget_dispose_template()` as necessary

src/libvalent/device/valent-device-impl.c, src/libvalent/device/valent-device.c, tests/libvalent/device/test-device-manager.c, tests/libvalent/device/test-device.c
This is only ever used for selecting an icon, which itself is a device property, while the channel identity holds actual capabilities.
Remove the property for now, as it can be acquired from the channel if necessary, or added later if it becomes convenient.
=> refactor(device): remove `ValentDevice:type` property

src/libvalent/device/valent-device-manager.c, src/plugins/clipboard/valent-clipboard-plugin.c, src/plugins/connectivity_report/valent-connectivity_report-plugin.c, src/plugins/contacts/valent-contacts-plugin.c, src/plugins/lan/valent-lan-channel-service.c, src/plugins/mousepad/valent-mousepad-plugin.c, src/plugins/mpris/valent-mpris-plugin.c, src/plugins/notification/valent-notification-plugin.c, src/plugins/photo/valent-photo-plugin.c, src/plugins/sftp/valent-sftp-plugin.c, src/plugins/share/valent-share-download.c, src/plugins/share/valent-share-plugin.c, src/plugins/systemvolume/valent-systemvolume-plugin.c, src/plugins/telephony/valent-telephony-plugin.c, tests/fixtures/valent-mock-device-plugin.c
Missing and invalid packet fields are worth noting in release builds, but shouldn't be concerning the user.
Replace all the reasonable instances of `g_warning()` with `g_debug()`.
=> refactor: downgrade packet fields from "warning" to "debug"

src/libvalent/contacts/valent-contacts-adapter.c, src/libvalent/contacts/valent-contacts-adapter.h, src/libvalent/contacts/valent-contacts.c, tests/libvalent/contacts/test-contacts-component.c
As with `Valent.Mixer` & `Valent.MixerAdapter`, port to `GListModel` to reduce API footprint and simplify internal management.
=> refactor(contacts): port ValentContactsAdapter to GListModel

src/libvalent/media/valent-media-player.c, src/libvalent/media/valent-media-player.h, src/libvalent/media/valent-media.c, src/plugins/mpris/valent-mpris-device.c, src/plugins/mpris/valent-mpris-impl.c, src/plugins/mpris/valent-mpris-player.c, src/plugins/mpris/valent-mpris-plugin.c, src/plugins/mpris/valent-mpris-remote.c, src/plugins/mpris/valent-mpris-remote.ui, src/plugins/mpris/valent-mpris-utils.h, tests/fixtures/valent-mock-media-player.c, tests/libvalent/media/test-media-component.c, tests/plugins/mpris/test-mpris-component.c, tests/plugins/mpris/test-mpris-impl.c, tests/plugins/mpris/test-mpris-plugin.c
There's no need for this cluttering the public API.
=> refactor(media): remove the play-pause method

src/libvalent/ui/valent-menu-list.c, src/libvalent/ui/valent-window.c, tests/fixtures/valent-test-utils.c, tests/fixtures/valent-test-utils.h, tests/libvalent/device/test-device-transfer.c, tests/libvalent/session/test-session-component.c, tests/libvalent/ui/meson.build, tests/libvalent/ui/test-device-page.c, tests/libvalent/ui/test-menu-stack.c, tests/libvalent/ui/test-window.c, tests/plugins/fdo/test-fdo-notifications.c, tests/plugins/fdo/test-fdo-session.c, tests/plugins/findmyphone/test-findmyphone-plugin.c, tests/plugins/gtk/test-gtk-notifications.c, tests/plugins/lan/test-lan-plugin.c, tests/plugins/notification/test-notification-plugin.c, tests/plugins/share/test-share-download.c
Cleanup a few tests and increase the coverage by exercising some code paths.
* refactor: rename `valent_test_wait()` to `valent_test_await_timeout()`
* refactor: various code style cleanups
* fix(ui): use-after-free in `ValentWindow` and `ValentMenuList`
* test: add more real-world checks for the main window
* test: add `test-menu-stack` and test the stack/list more
=> test: cleanups and coverage increases

src/plugins/sms/valent-sms-store.c, tests/extra/cppcheck.supp
`ValentMessageStore` defers signal emissions to the main thread, but was not using a thread safe struct.
=> fix(sms): fix data races in signal emission

src/libvalent/ui/meson.build, src/libvalent/ui/valent-application.c, src/libvalent/ui/valent-device-page.h, src/libvalent/ui/valent-device-preferences-window.c, src/libvalent/ui/valent-device-preferences-window.h, src/libvalent/ui/valent-media-remote.h, src/libvalent/ui/valent-preferences-window.h, src/libvalent/ui/valent-ui-main.c, src/libvalent/ui/valent-ui-utils.c, src/libvalent/ui/valent-ui-utils.h, src/libvalent/ui/valent-window.c, src/libvalent/ui/valent-window.h, src/libvalent/ui/valent-window.ui, tests/fixtures/valent-test-utils.c, tests/libvalent/ui/test-device-page.c, tests/libvalent/ui/test-device-preferences-window.c, tests/libvalent/ui/test-media-remote.c, tests/libvalent/ui/test-menu-stack.c, tests/libvalent/ui/test-preferences-window.c, tests/libvalent/ui/test-window.c
Add a function similar to `gtk_init_check()` that can be used to initialize assets for Valent's default user interface.
=> feat(ui): add `valent_ui_init()`

src/plugins/runcommand/ca.andyholmes.Valent.Plugin.runcommand.gschema.xml, src/plugins/runcommand/valent-runcommand-plugin.c
The `isolate-subprocesses` setting defaulted to `true`, while the UI for changing it was previously removed. This made running commands on the host effectively impossible.
Remove the `isolate-subprocesses` setting until the preferences have been rewritten.
closes #450
=> fix(runcommand): remove the `isolate-subprocesses` setting

src/libvalent/clipboard/valent-clipboard.c, src/libvalent/contacts/valent-contacts.c, src/libvalent/core/valent-component.c, src/libvalent/input/valent-input.c, src/libvalent/media/valent-media.c, src/libvalent/mixer/valent-mixer.c, src/libvalent/notifications/valent-notifications.c, src/libvalent/session/valent-session.c, src/libvalent/ui/style.css, src/libvalent/ui/valent-media-remote.ui
Remove `Valent.Component:plugin-priority` key, since it can reliably be inferred from the `:plugin-type`.
=> refactor(component): infer the priority key

src/plugins/lan/valent-lan-channel-service.c
Use the result of `g_get_num_processors()`, which is more or less the number of cores, as the number of threads to spawn for `GThreadedSocketService`.
=> refactor(lan): use the number of CPUs as the thread count for service

src/plugins/battery/valent-battery-plugin.c
Don't send an unsolicited battery update at connect time, since there is a packet for requesting this devices should send.
=> refactor(battery): don't send connect-time update unsolicited

src/libvalent/core/valent-debug.c
Set the default log handler to `g_log_default_handler` when `valent_debug_clear()` is called.
=> fix(libvalent): properly restore the default log handlers at shutdown

src/libvalent/device/valent-device-manager.c
This was previously in `ValentApplication`, but must now live in `ValentDeviceManager`'s `startup()` vfunc.
=> fix(device): revive the Device Name setting

src/libvalent/device/valent-device-manager.c, src/libvalent/device/valent-device.c, src/plugins/battery/valent-battery-plugin.c, src/plugins/clipboard/valent-clipboard-plugin.c, src/plugins/connectivity_report/valent-connectivity_report-plugin.c, src/plugins/connectivity_report/valent-telephony.c, src/plugins/contacts/valent-contacts-plugin.c, src/plugins/findmyphone/valent-findmyphone-plugin.c, src/plugins/lock/valent-lock-plugin.c, src/plugins/mousepad/valent-mousepad-plugin.c, src/plugins/mpris/valent-mpris-impl.c, src/plugins/mpris/valent-mpris-player.c, src/plugins/mpris/valent-mpris-plugin.c, src/plugins/mpris/valent-mpris-utils.c, src/plugins/notification/valent-notification-plugin.c, src/plugins/photo/valent-photo-plugin.c, src/plugins/ping/valent-ping-plugin.c, src/plugins/presenter/valent-presenter-plugin.c, src/plugins/runcommand/valent-runcommand-plugin.c, src/plugins/sftp/valent-sftp-plugin.c, src/plugins/share/valent-share-plugin.c, src/plugins/sms/valent-sms-plugin.c, src/plugins/sms/valent-sms-utils.c, src/plugins/systemvolume/valent-systemvolume-plugin.c, src/plugins/telephony/valent-telephony-plugin.c, tests/fixtures/valent-mock-device-plugin.c, tests/fixtures/valent-test-fixture.c
When first fetching the `CanRaise` property, set it to `TRUE` if there is a default `GApplication`. Then if `Raise()` is called on the application interface of an exported player, activate `app.media-remote` to open the default media remote.
=> feat(mpris): open the media remote when `Raise()` is called

src/libvalent/core/valent-global.c, src/plugins/clipboard/valent-clipboard-plugin.c, src/plugins/gnome/valent-gnome-clipboard.c, tests/plugins/clipboard/test-clipboard-plugin.c, tests/plugins/gnome/mock_gnome_clipboard.py, tests/plugins/gnome/test-gnome-clipboard.c
Add another hidden environment variable, `VALENT_PLUGIN_LOADERS`, to control whether Python3 plugins can be loaded.
=> refactor(core): disable Python plugins by default

src/plugins/clipboard/valent-clipboard-plugin.c, tests/plugins/clipboard/test-clipboard-plugin.c
Signal timing has proved to be unreliable, relative to packet communication, so avoid recursion by comparing to the remote content.
=> fix(clipboard): actually fix infinite loop

doc/schemas/kdeconnect.mpris.json, doc/schemas/kdeconnect.mpris.request.json, src/plugins/mpris/valent-mpris-plugin.c
There were a few undocumented field for the `mpris` plugin, which were also therefore not being fuzzed in tests.
=> docs: add missing album art fields to protocol reference

build-aux/flatpak/ca.andyholmes.Valent.Devel.json, build-aux/flatpak/ca.andyholmes.Valent.json, src/plugins/lan/valent-lan-channel-service.c, tests/extra/cppcheck.supp
Allow the LAN channel service to listen on any TCP port within the protocol range for incoming connections, and ensure the identity packet contains the correct `tcpPort` value.
Flatpak maintenance.
closes #493
=> fix(lan): support multiple adaptive listening port

src/libvalent/core/valent-extension.c, src/libvalent/core/valent-extension.h
Remove a casting macro for `valent_extension_get_object()` and just use `gpointer` with the `(type GObject.Object)` annotation.
Always check the extension's error pointer, instead of the incoming argument.
=> refactor(core): remove a cast-macro and other minor cleanups

doc/schemas/kdeconnect.battery.request.json, doc/schemas/kdeconnect.connectivity_report.request.json, doc/sdk/protocol.py, src/plugins/battery/battery.plugin.desktop.in, src/plugins/battery/valent-battery-plugin.c, src/plugins/connectivity_report/connectivity_report.plugin.desktop.in, src/plugins/connectivity_report/valent-connectivity_report-plugin.c, tests/extra/cppcheck.supp, tests/fixtures/data/plugin-battery.json, tests/fixtures/data/plugin-connectivity_report.json, tests/plugins/battery/test-battery-gadget.c, tests/plugins/battery/test-battery-plugin.c, tests/plugins/connectivity_report/test-connectivity_report-gadget.c, tests/plugins/connectivity_report/test-connectivity_report-plugin.c
Remove support for `kdeconnect.battery.request` and `kdeconnect.connectivity_report.request`.
=> refactor(plugins): remove deprecated packets

.github/workflows/ci.yml, src/plugins/battery/valent-battery-plugin.c, tests/plugins/battery/mock_upower.py, tests/plugins/battery/test-battery-plugin.c, tests/plugins/battery/test-battery.c
* fix(battery): always send the battery status at connect-time
* fix(battery): fix timeouts in `test-battery-plugin`
* fix(ci): add pylintrc to pre-test options
=> test: various fixes

src/libvalent/core/valent-object.c, src/plugins/lan/valent-lan-channel-service.c, tests/extra/cppcheck.supp, tests/fixtures/valent-mock-channel.c
* fix(lan): stash port while holding the lock
* refactor: move a static lock into its function scope
* refactor: error if a `ValentObject` subclass overrides `dispose()` and remove a defunct critical
=> refactor: various minor cleanups

src/libvalent/media/valent-media.c
`ValentMediaPlayer` instances were only exported on adapters that were available for the first call to `valent_media_export_player()`.
Media players marked for export are now exported when the `ValentMedia` component binds a new adapter.
closes #476
=> fix(media): ensure players are exported on new and existing adapters

build-aux/flatpak/ca.andyholmes.Valent.Devel.json
Both libdex and sysprof will be included in runtime soon (yay!), so
remove them now rather than chasing incremental commits in the upstream
build systems.
=> build(flatpak): remove sysprof from devel flatpak 

src/libvalent/ui/valent-window.ui, src/plugins/connectivity_report/valent-connectivity_report-preferences.c, src/plugins/connectivity_report/valent-connectivity_report-preferences.ui, src/plugins/notification/valent-notification-preferences.ui, src/plugins/sms/valent-sms-window.ui, src/plugins/telephony/valent-telephony-preferences.ui
Cleanup a variety of minor UI elements, porting to `Adw.StatusPage`, removing unused template pointers, and other various tweaks.
=> refactor(ui): various UI cleanups

.github/workflows/ci.yml
There's no real need for this, and this should allow flatpak tests to run on forks.
=> ci: don't GPG sign flatpaks in test builds

build-aux/contrib/valent.spec, build-aux/flatpak/ca.andyholmes.Valent.Devel.json, build-aux/flatpak/ca.andyholmes.Valent.json, meson.build, subprojects/libportal.wrap
Raise the minimum version to 0.6, since that'll be around for awhile.
closes #560
closes #569
=> build(deps): bump libportal to 0.7.1

src/libvalent/device/valent-device-private.h, src/libvalent/device/valent-device.c, tests/fixtures/valent-test-fixture.c, tests/fixtures/valent-test-utils.c, tests/fixtures/valent-test-utils.h, tests/libvalent/clipboard/test-clipboard-component.c, tests/libvalent/device/test-certificate.c, tests/libvalent/device/test-device-manager.c, tests/libvalent/device/test-device.c, tests/plugins/battery/test-battery-plugin.c, tests/plugins/clipboard/test-clipboard-plugin.c, tests/plugins/connectivity_report/test-connectivity_report-plugin.c, tests/plugins/gtk/test-gdk-clipboard.c, tests/plugins/lan/test-lan-dnssd.c, tests/plugins/lan/test-lan-plugin.c, tests/plugins/lock/test-lock-plugin.c, tests/plugins/mousepad/test-mousepad-plugin.c, tests/plugins/systemvolume/test-systemvolume-plugin.c, tests/plugins/telephony/test-telephony-plugin.c
Remove `valent_device_handle_packet()` from the private header, in an effort to stop exposing private symbols to test fixtures.
=> refactor(device): stop exporting a private method

build-aux/docker/Dockerfile
libpeas-2 is not available in `fedora:39`, and fussing with a subproject is not really worth the trouble at this point.
Add build and install the dependency in the CI, so test can be run until its available or someone reports it as a necessity.
=> ci: add libpeas-2 to the Dockerfile

src/plugins/lan/valent-lan-utils.c
The TLS helpers in the LAN plugin were not always checking the correct path for stored certificates. Fix this and add a TODO for a more permanent solution.
=> fix(lan): use the correct path for certificates

build-aux/docker/Dockerfile
libpeas-2 is now available in fedora-updates
=> ci: stop building libpeas in the container

build-aux/flatpak/ca.andyholmes.Valent.json, src/libvalent/ui/valent-ui-manager.c, src/libvalent/ui/valent-ui-utils-private.h, src/libvalent/ui/valent-ui-utils.c, src/libvalent/ui/valent-window.c, src/plugins/lan/valent-lan-channel-service.c, tests/extra/cppcheck.cfg, tests/extra/cppcheck.supp
closes #611
closes #615
closes #619
=> build(flatpak): bump evolution-data-server and libpeas

src/plugins/share/valent-share-target.c
Remove an unused and redundant call to `g_ptr_array_find()`.
=> fix: remove redundant function call

src/libvalent/core/valent-component.c
Apparently this is, or always was, `GObject.Type` rather than `GLib.Type` as one would expect, were they the sort for run-on sentences and the like.
=> fix: use correct gi-docgen reference

src/libvalent/device/valent-certificate.c, src/libvalent/device/valent-certificate.h
There were some errant includes of built-time private headers causing external builds fail (e.g. plugins).
=> fix: private header includes

doc/schemas/kdeconnect.identity.json, src/libvalent/device/valent-certificate.c, src/libvalent/device/valent-device-manager.c, src/libvalent/device/valent-device.c, src/libvalent/device/valent-device.h, tests/plugins/lan/test-lan-plugin.c
Add `valent_device_generate_id()` and adopt it for use throughout
Valent, including tests. Existing test vectors are left as-is for
now, although later tests should be added for generating compliant
IDs and accepting backward-compatible IDs.
closes #643
=> feat: adopt standardized KDE Connect device ID

src/libvalent/ui/valent-ui-manager.c, src/plugins/findmyphone/valent-findmyphone-ringer.c, src/plugins/runcommand/valent-runcommand-preferences.c, src/plugins/share/valent-share-plugin.c, src/plugins/sms/valent-sms-plugin.c
The `select-multiple` property was a carry-over from `GtkFileChooser`.
=> fix(share): remove defunct property

src/libvalent/media/valent-media-player.h, src/plugins/mpris/valent-mpris-player.c
It's not clear why chaining a cancellable would result in an object
self-disposing, or why it doesn't happen during the initial polling
of active players, but it's unnecessary here anyways.
closes #655
=> fix(mpris): fix players self-disposing during initialization

.github/workflows/cd.yml, .github/workflows/ci.yml
This will keep failing and the coverage report is posted publicly, so just drop the dependency.
=> ci: drop the coveralls.io check

src/plugins/findmyphone/valent-findmyphone-plugin.c
It would nice if there were a way to notify without unlocking, but it's possible someone might ring their phone and find it in someone else's hands.
Remove this behaviour for now, since better safe than sorry.
closes #663
=> fix(findmyphone): don't unlock when ringing

src/plugins/systemvolume/valent-systemvolume-device.c, tests/extra/cppcheck.supp, tests/plugins/systemvolume/test-systemvolume-plugin.c
Sinks are sent at connect time and updated as necessary, so drop the request command.
See:
- https://invent.kde.org/network/kdeconnect-android/-/merge_requests/500
- https://invent.kde.org/network/kdeconnect-kde/-/merge_requests/756
- https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1890
=> refactor(systemvolume): don't send `requestSinks` command at connect

.github/workflows/cd.yml
=> ci: use GitHub-hosted arm64 runner for aarch64 Flatpak build

src/libvalent/device/valent-channel.c
During a refactor, the incorrect certificate was being stored effectively storing the local certificate as though it were the remote certificate.
closes #769
=> fix(device): save correct certificate for device

src/libvalent/device/valent-device-plugin.c, src/libvalent/device/valent-device.c
Due to the way device connections can be "hot swapped", while incoming packets resolve asynchronously, it's possible for a device to receive packets while technically disconnected.
Address this by tracking the device state and stashing incoming packets to prevent violating what should be an invariant that plugins rely on. Not handling this results in non-deterministic crashes that are likely more annoying than missing a few packets.
=> fix(device): add a temporary fix for device plugins

src/libvalent/device/valent-device.c, tests/libvalent/device/test-device.c
Optimize the device name and ID functions to avoid the regex and maintain thread-safety.
=> refactor(device): optimize device name and ID validation functions

src/libvalent/device/valent-channel-service.c, src/libvalent/device/valent-device-manager.c
Remove certificates with invalid device IDs and
regenerate them at the correct path in the
channel service.
closes #807
=> fix(device): regenerate certificates with invalid device IDs

meson.build, po/en.po, po/es.po, po/fr.po, po/it.po, po/nl.po, po/pt_BR.po, po/te.po, po/valent.pot, po/zh_CN.po, src/libvalent/contacts/valent-contact.c, src/libvalent/meson.build, src/plugins/gnome/valent-preferences-dialog.c, src/plugins/gnome/valent-preferences-dialog.ui, tests/extra/lsan.supp, tests/extra/tsan.supp
Check the device name entry for valid input and inform the user of the contraints if they're violated.
=> feat(gnome): check device name entry for validity

build-aux/flatpak/ca.andyholmes.Valent.Devel.json, build-aux/flatpak/ca.andyholmes.Valent.json
Apaprently this has been in the runtime for awhile, and we don't need anything fancy to justify building the latest.
=> build(flatpak): don't build pipewire

build-aux/flatpak/ca.andyholmes.Valent.Devel.json, build-aux/flatpak/ca.andyholmes.Valent.json, src/plugins/sftp/valent-sftp-plugin.c
Some distributions or desktop environments don't seem to handle `sftp` URIs properly, so prefer the XDG interface over GIO's `g_app_info_launch_default_for_uri_async()`.
closes #597
cc #429
=> refactor(sftp): prefer org.freedeskop.FileManager1 for URIs

po/en.po, po/es.po, po/fr.po, po/it.po, po/nl.po, po/pt_BR.po, po/te.po, po/valent.pot, po/zh_CN.po, src/plugins/sftp/valent-sftp-plugin.c
Add support for the full path listing, allowing the device to
be mounted, unmounted and folders browsed from the menu.
This doesn't allow mounting individual folders as discrete
paths, but does give an entry point for browsing them when a
device exposes paths outside the root folder.
closes #429
=> feat(sftp): add an expanded menu and actions
